// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRpYrz1MGfuxdTd8-p0NaO9753y8meTmY',
    appId: '1:1065968135170:web:3a6aaf09f1894a4c6b8b1b',
    messagingSenderId: '1065968135170',
    projectId: 'todo-app-1e07e',
    authDomain: 'todo-app-1e07e.firebaseapp.com',
    databaseURL: 'https://todo-app-1e07e-default-rtdb.firebaseio.com',
    storageBucket: 'todo-app-1e07e.firebasestorage.app',
    measurementId: 'G-5Y94411ZKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdRTDXcCgFz79_jY1Yq3NPOAtWX2f2zw4',
    appId: '1:1065968135170:android:a5533869f85360226b8b1b',
    messagingSenderId: '1065968135170',
    projectId: 'todo-app-1e07e',
    databaseURL: 'https://todo-app-1e07e-default-rtdb.firebaseio.com',
    storageBucket: 'todo-app-1e07e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRpYrz1MGfuxdTd8-p0NaO9753y8meTmY',
    appId: '1:1065968135170:web:62b8089dd8db2dbd6b8b1b',
    messagingSenderId: '1065968135170',
    projectId: 'todo-app-1e07e',
    authDomain: 'todo-app-1e07e.firebaseapp.com',
    databaseURL: 'https://todo-app-1e07e-default-rtdb.firebaseio.com',
    storageBucket: 'todo-app-1e07e.firebasestorage.app',
    measurementId: 'G-S8531THR8X',
  );

}